version: '3.4'

services:
  mongodb:
    image: aashreys/mongo-auth:latest
    volumes:
      - ./mongodb-data:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin
      - MONGODB_APPLICATION_DATABASE=app
      - MONGODB_APPLICATION_USER=app
      - MONGODB_APPLICATION_PASS=app
    networks:
      - backend

  nginx:
    image: nginx:1.13.10-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default/:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - app
    networks:
      - frontend

  app:
    build: .
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /etc/localtime:/etc/localtime:ro
    working_dir: "/usr/src/app"
    command: gunicorn -w 2 -b :8000 app:app
    restart: on-failure:5
    networks:
      - frontend
      - backend
    #env_file:
      #- .env
    environment:
      - LANG=C.UTF-8
      - APP_ENVIRONMENT=production

networks:
  frontend:
    driver: bridge #or overlay in swarm mode
  backend:
    driver: bridge #or overlay in swarm mode
