version: '3.4'

services:
  mongodb:
    image: aashreys/mongo-auth:latest
    #ports:
      #- "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin
      - MONGODB_APPLICATION_DATABASE=app
      - MONGODB_APPLICATION_USER=app
      - MONGODB_APPLICATION_PASS=app

  nginx:
    image: nginx:1.13.10-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default-ssl/:/etc/nginx/conf.d
      - ./certs/:/certs/
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - app

  app:
    build: .
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /etc/localtime:/etc/localtime:ro
    working_dir: "/usr/src/app"
    command: python run.bjoern.py
    restart: on-failure:5
    #env_file:
      #- .env
    environment:
      - LANG=C.UTF-8
      - APP_ENVIRONMENT=production
